### PR TITLE
Updates README.md

### PR DESCRIPTION
**Pull request by thedarkspy**
- Adds a new company (BlockStead) for automated smart contract security audits

### CODE REVIEW

**Comment by 0xNazgul** [comment]
Not going to add this

**Comment by boshmaf** [comment]
Hi @0xNazgul, any reason why?

**Comment by 0xNazgul** [comment]
No public audits and looks like a scam GL

**Comment by boshmaf** [comment]
Thank you for your feedback but I’m not sure what you mean — there are more than 100k public audits. Have you even checked the website? Pick any report of recent audits or top-risky contracts here: [https://app.blockstead.io](https://app.blockstead.io).

They guy who made the PR linked to a test landing page which is obsolete. I recommend using the link above. It’s also free for basic. If you don’t want to add it to your list that’s fine. People can reach it from somewhere else. Just trying to help.

**Comment by 0xNazgul** [comment]
I did look at the website and he had linked both the outdated and the one you mention in his PR. You say that your "100k audits" are public however you charge to see them? I don't want to promote a scam around selling automated reports when they can go to any other blockchain security company to read quality reports.

**Comment by boshmaf** [comment]
That’s very thoughtful of you.

You might have missed it, but the basic service is free — you can view 500 audit reports and perform 5 audits. It uses multiple proprietary and open-source code analyzers that any auditor with some exposure to the field knows. Some of the analyzers are often used in manual audits by firm like Trail of Bits, Certik, Consensys Diligence, etc.

Other than viewing public audits for free, the core functionality of the service is on-demand automated security auditing of smart contracts that can be integrated into your favorite CI/CD system or web3 framework, similar to MythX. It does not replace manual auditing, it just raises the bar for the actual work done by auditors, as it allows developers to fix many of the most important vulnerabilities before they go for a manual audit. Many people find that useful.

Anyway, thank you for curating this public list. It’s been useful. Keep it up.

**Pull request closed without merging**
